---
title: "Summaries"
author: "Robert Esposito"
format: pdf
---

# Article Summaries

Note: If I can't find the article yet, I just put the abstract. 

## @stephens1989language

Portuguese in USA. Arrivals began in 1820s, picked up in 1830s with arrival fo Lusitanian and Azorean. Congregated to New England, specifically MA. 1850s, to California (San Fran).

Late 19th/early 20th century, big influx to CA, MA, NY, & NJ. Mid-1970s, major immigration event.

Early immigrants = high illiteracy, low English.

Azorean Portuguese is stigamized [@middleton1986language].

Began arriving to MNeark in large groups in 1920s [@cunha1981portugueses].

Bilingual programs (I guess school programs?) & Sunday schools. 15 private Portuguese schools, similar to Hebrew schools.

## @caravalho201014

Portuguese immigrants mainly from Azores Islands, mainland Portugual, and Cape Verdean, smaller population from Mozambique and Angola. High concentrations in MA. Over last 20 years, Cape Verdeans & Brazilians account for most PT speakers.

14,829 students taking Portuguese classes in K-12 schools in 2008 [@vicente2008promoccao].

Modern Language Association in 2006 reported 22.4% increase of availability of Portuguese instruction between 2002 and 2006.

US Census underestimates PT speakers in USA. Ministry of Foreign Affairs in Brazil report much higher estimate. Due to undocumented immigrants.

National Bilingual Education Act of 1968 resulted in PT-EN bilingual education initiatives in 1970s.

Republic of Cape Verde immigrants speak a Portuguese-based creole and Portuguese. They typically are more receptive bilinguals than e.g., Azorean or Madeiran speakers in the US (Ferreira 2005; need to find bibtex). Cape Verdean-Americans tend to be L1 Crole L1 EN/L2 EN, and then may learn PT as L3 in school.

Brazilian immigration in 1984-1987, again in 1990s. Young, educated, middle-class men and women on tourist visas and overstayed (Bensabat-Ott 2000; need to find bibtex). Later, working class immigrants from small towns and rural areas who entered via US-Mexico border.

Luso-American Foundation (FLAD, Fundacao Luso-Americana de Desenvolvimento) identified `r 52 + 25 + 20 + 17 + 13 + 10 + 5 +1` K-12 public and community schools that offer Portuguese. 20 in NJ, 10 in NY, 13 in CT; weekend Portuguese language schools in NJ [@vicente2008promoccao].

Dual-immersion EN-PT program in K-8 school in MA resulted in greater awareness of dialectal differences among teachers, parents, and staff [@rubinstein2002problematizing].

Dialectal differences do not result in communicative breakdown between students (Rubinstein-Avila, 2002; Ferreira, 2005).

## @osborne2021perception

Mid vowel contrasts as the last to be acquired by L1 speakers (Matzenauer & Costa, 2017). Low functional load with few minimal pairs (Alves, 2008).

12 BR-PT heritage speakers. Completed BLP (all except one was English-dominant, but pretty large range).

AXB discrimination. Check article for list of stimuli.

2AFC identification task.

Heritage speakers accurately categorize PT mid vowels, but higher EN dominance predicted more trouble with /ɔ/-/o/. Amengual (2015) found the same asymmetry for ES-Catalan bilinguals. 

## @rothman2014portuguese

No studies examining Cape Verdean Portuguese as a heritage language. (Although, as noted by @caravalho201014, they would be learning Cape Verdean Creole at home).

PT-PT stops are pronounced as fricatives; BR-PT pronounces as plosives. Would be interesting to see if PT-PT maintains fricatives in Newark given input from BR-PT and English.

Summary of heritage speakers learning in college, focused on dialectal differences [@silva2010starting].

## @silva2010starting

Developing a heritage speaker track in college for PT. Focus on dialectal differences.

## @galves2005syntax
Syntactic position of clitic pronouns (e.g., *me, te, se, o, lhe*) in EP and BP arise from both syntactic and morphophonological factors. The authors argue that EP clitics attach to Infl (inflectional category) and BP clitics attach to the verb (V) in the syntactic structure. Additionally, the authors argue that EP does not permit clitics in sentence-initial position, whereas BP does not have this restriction. This results in a strong preference for enclisis (post-verbal clitic) in EP (*chamou-me*), and a preference for proclisis (pre-verbal clitic) in BP (*me chamou*). In multi-verb constructions, EP clitics attach to the finite verb (*tinham-se entendido perfeitamente*), while in BP they tend to attach to the non-finite verb (*tinham se entendido perfeitamente*)

## @amadeo2025perception

Escudero et al. (2009; "A cross-dialect acoustic description of vowels: Brazilian and European Portuguese) and Rato & Carlet (2020) show that BR-PT and PT-PT share some similarities in their vowel inventory.

Diaz-Granado (2011) found that /e ~ ɛ/ in English & Portuguese are not similar, so L1 En L2 Pt are expected to collapse PT /e ~ ɛ/ into a single category. Tested L1 En L2 Pt and L1 En L2 Es L3 Pt. L3 learners performed better. But there were only 12 in the first group, 5 in the second.

Kendall (2004) tested 20 beginning and advanced L1 En L2 Pt learners on BP mid vowels. They did poorly.

Vasiliev (2013) tested L1 English L2 Pt stressed oral vowels. /e ~ ɛ/ was second-easiest.

Elvin et al. (2018) L1 En monolinguals, En-Es bilinguals tested on discrimination task for Pt-Pt and Pt-Br. /o ~ ɔ/ easier in EP than BP, which was second-easiest to discriminate. Participants had more trouble with /i ~ e/ and /u ~ o/.

Summary: For L1 US En, /e ɛ o c/ are hardest to discriminate; /e ~ ɛ, o ~ ɔ, e ~ i, o ~ u/ are most challenging minimal pairs. These challenges are accurately predicted by perception models e.g., Escudero 2009.

NEED TO FINISH THIS SUMMARY AND ALSO FIND ALL OF THESE ARTICLES.

# Topic Summaries

# Misc.

Fernanda A. Ferreira has a lot of research on heritage speakers in college classes.